# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb2e6a926aa8acc45211378272ad49aba2c0e18b35922b31dcada56ab438c3c51482b26843d907bbe4d763e0eb5fad4b9680606f9d751f1e21b055bfacbe7b87

test:
  secret_key_base: e2b3d6e57240c4337b6685b5a0a1c920f3c0046aed8ce2f4606fe6dbe085634b30155c956fae741ef9fce854dd6978f65a3a7f50a705b1413368c18e583b0b7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
